version: "3.8"

services:
  course:
    image: getclass/course:latest
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
    volumes:
      - ./category_photos/:/category_photos/
      - ./course_photos/:/course_photos/
    networks:
      main:
        aliases:
          - course
networks:
  main:
    external: true